ci: HACK: Pin flake8 python to 3.11
With Python 3.12 and 3.13, flake8 fails:

```
   eps = importlib_metadata.entry_points().get(self.namespace, ())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

This is somehow related to https://github.com/PyCQA/flake8/issues/1701
and https://github.com/python/importlib_metadata/issues/406. We can't
use the former `import_metadata < 5` workaround any more, as flake8
imports this library from Python's stdlib (`importlib.metadata`), so the
external module gets ignored.

I don't know how to fix that. As the Python version that flake8 runs
with isn't very interesting, pin it to 3.11 for the time being.